export const SUBSCRIBE = 'SUBSCRIBE'
export const UNSUBSCRIBE = 'UNSUBSCRIBE'
export const SUBSCRIPTION_DETAIL_REQUEST = 'SUBSCRIPTION_DETAIL_REQUEST'
export const SUBSCRIPTION_DETAIL_SUCCESS = 'SUBSCRIPTION_DETAIL_SUCCESS'
export const SUBSCRIPTION_DETAIL_FAIL = 'SUBSCRIPTION_DETAIL_FAIL'

