export const SUBSCRIBE_REQUEST = 'SUBSCRIBE_REQUEST'
export const SUBSCRIBE_SUCCESS = 'SUBSCRIBE_SUCCESS'
export const SUBSCRIBE_FAIL = 'SUBSCRIBE_FAIL'

export const UNSUBSCRIBE = 'UNSUBSCRIBE'
export const SUBSCRIPTION_DETAIL_REQUEST = 'SUBSCRIPTION_DETAIL_REQUEST'
export const SUBSCRIPTION_DETAIL_SUCCESS = 'SUBSCRIPTION_DETAIL_SUCCESS'
export const SUBSCRIPTION_DETAIL_FAIL = 'SUBSCRIPTION_DETAIL_FAIL'

export const SUBSCRIPTION_UPDATE_REQUEST = 'SUBSCRIPTION_UPDATE_REQUEST'
export const SUBSCRIPTION_UPDATE_SUCCESS = 'SUBSCRIPTION_UPDATE_SUCCESS'
export const SUBSCRIPTION_UPDATE_FAIL = 'SUBSCRIPTION_UPDATE_FAIL'
