export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'

export const USER_ADD_ADDRESS_REQUEST = 'USER_ADD_ADDRESS_REQUEST'
export const USER_ADD_ADDRESS_SUCCESS = 'USER_ADD_ADDRESS_SUCCESS'
export const USER_ADD_ADDRESS_FAIL = 'USER_ADD_ADDRESS_FAIL'

export const USER_GET_ADDRESS_REQUEST = 'USER_GET_ADDRESS_REQUEST'
export const USER_GET_ADDRESS_SUCCESS = 'USER_GET_ADDRESS_SUCCESS'
export const USER_GET_ADDRESS_FAIL = 'USER_GET_ADDRESS_FAIL'

export const USER_UPDATE_ADDRESS_REQUEST = 'USER_UPDATE_ADDRESS_REQUEST'
export const USER_UPDATE_ADDRESS_SUCCESS = 'USER_UPDATE_ADDRESS_SUCCESS'
export const USER_UPDATE_ADDRESS_FAIL = 'USER_UPDATE_ADDRESS_REQUEST'
