export const WAITLIST_REQUEST = 'WAITLIST_REQUEST'
export const WAITLIST_SUCCESS = 'WAITLIST_SUCCESS'
export const WAITLIST_FAIL = 'WAITLIST_FAIL'

export const WAITLIST_ADD_ITEM = 'WAITLIST_ADD_ITEM'
export const WAITLIST_REMOVE_ITEM = 'WAITLIST_REMOVE_ITEM'

export const WAITLIST_ADD_ITEM_REQUEST = 'WAITLIST_ADD_ITEM_REQUEST'
export const WAITLIST_ADD_ITEM_SUCCESS = 'WAITLIST_ADD_ITEM_SUCCESS'
export const WAITLIST_ADD_ITEM_FAIL = 'WAITLIST_ADD_ITEM_FAIL'
