export const WISHLIST_REQUEST = 'WISHLIST_REQUEST'
export const WISHLIST_SUCCESS = 'WISHLIST_SUCCESS'
export const WISHLIST_FAIL = 'WISHLIST_FAIL'
export const UNAUT_WISHLIST = 'UNAUT_WISHLIST'

export const WISHLIST_ADD_ITEM = 'WISHLIST_ADD_ITEM'
export const WISHLIST_REMOVE_ITEM = 'WISHLIST_REMOVE_ITEM'

export const WISHLIST_ADD_ITEM_REQUEST = 'WISHLIST_ADD_ITEM_REQUEST'
export const WISHLIST_ADD_ITEM_SUCCESS = 'WISHLIST_ADD_ITEM_SUCCESS'
export const WISHLIST_ADD_ITEM_FAIL = 'WISHLIST_ADD_ITEM_FAIL'
